### ISSUE TITLE
flups without openMP

### ISSUE THREAD

**Issue by bderembl** [vortexlab-uclouvain/flups#4]
Hi
I am trying to compile and run FLUPS without openMP so that it is compatible with another library that does not support openMP. 

I have removed the -fopenmp flag in the makefile
I also changed the couple of lines that hardcoded the use of openmp:

chunk_tools.cpp:    fftw_plan_with_nthreads(omp_get_max_threads());
Solver.cpp:    fftw_init_threads();
Solver.cpp:    fftw_cleanup_threads();
SwitchTopo.cpp:    fftw_plan_with_nthreads(omp_get_max_threads());

In principle it should work but I still get this error when trying to compile an example without the -fopenmp flag:

/usr/bin/ld: .../lib/libflups_nb.a(nb_Solver.o): undefined reference to symbol 'omp_get_num_threads@@OMP_1.0'
/usr/bin/ld: /lib/libgomp.so.1: error adding symbols: DSO missing from command line

Do you have any recommendation on the way to proceed to compile FLUPS without openMP?

Thank you

**Comment by thomasgillis** [comment]
Hi @bderembl thanks for reaching out, and sorry for the delay.

We don't have a solution for now (@pbalty is working on one as we speak, but he has a lot on his plate for the moment).
However, as you noticed the `pragma` are going to be ignored, just the API symbols must be solved at link time.
Adding `-fopenmp` (included in all modern compilers) should be able to help you and not interfere with the other code

**Comment by pbalty** [comment]
Hi @bderembl, 
I just introduced a new compilation flag, `WITHOUT_OPENMP`, and pushed everything on the repo (`v2.2`). 
Everything compiles and runs on my computer without the `-fopenmp` flag. Let me know if it works on your side.

**Comment by bderembl** [comment]
Hi @pbalty,

It works great, thank you very much!

One more quick thing (I can open a new issue if you prefer). in flups.h is it possible to change
`#include "mpi.h"`
into
`#include <mpi.h>`


same for 
`#include "stdlib.h"`
into
`#include <stdlib.h>`

just to appease my compiler

Thanks again for your reactivity, I really appreciate.

**Comment by pbalty** [comment]
I have just done it! 
You are welcome, it's always a pleasure to have tips to improve our library. 

I close the issue, since it has been fixed in 11240dc .
